Repository elastic/eland, pull requests merged in 2021-11, with the labels that each got.

#409 Adds NLP with PyTorch basic example to README
  README.md
Labels: documentation, enhancement, topic:ml

#401 [ML] adding inference results tests for pytorch transformer models
  .ci/jobs/defaults.yml
  .ci/run-elasticsearch.sh
  eland/ml/pytorch/_pytorch_model.py
  tests/ml/pytorch/test_pytorch_model_pytest.py
Labels: ci, topic:ml

#411 Adds max_length padding to transformer tracing
  eland/ml/pytorch/transformers.py
Labels: bug, topic:ml

#413 Adds pytorch files to noxfile
  eland/ml/pytorch/_pytorch_model.py
  eland/ml/pytorch/transformers.py
  noxfile.py
Labels: bug, ci, topic:ml
