Repository elastic/eland, pull requests merged in 2022-01, with the labels that each got.

#284 Handle datetime types in comparison filters
  eland/series.py
  tests/series/test_arithmetics_pytest.py
Labels: hacktoberfest-accepted

#427 [ML] adding MPNet model support for pytorch
  eland/ml/pytorch/transformers.py
  tests/ml/pytorch/test_pytorch_model_pytest.py
Labels: enhancement, topic:ml

#428 [DOCS] Adds NLP with PyTorch section to ML-related page in Eland docs
  docs/guide/machine-learning.asciidoc
Labels: documentation, topic:ml
