Repository elastic/eland, pull requests merged in 2022-05, with the labels that each got.

#459 [ML] Improve NLP model import by using nicely defined types
  README.md
  bin/eland_import_hub_model
  eland/ml/pytorch/_pytorch_model.py
  eland/ml/pytorch/nlp_ml_model.py
  eland/ml/pytorch/transformers.py
  tests/ml/pytorch/test_pytorch_model_pytest.py
Labels: topic:ml

#457 [ML] add support for question_answering NLP tasks
  eland/ml/pytorch/nlp_ml_model.py
  eland/ml/pytorch/transformers.py
Labels: enhancement, topic:ml

#463 [ML] improve general pytorch model import and add tests
  eland/ml/pytorch/__init__.py
  eland/ml/pytorch/traceable_model.py
  eland/ml/pytorch/transformers.py
  tests/ml/pytorch/test_pytorch_model_upload_pytest.py
  tests/ml/pytorch/test_transformer_pytorch_model_pytest.py
Labels: enhancement, topic:ml

#465 [ML] fixes decision tree classifier upload to account for probabilities
  eland/ml/ml_model.py
  eland/ml/transformers/sklearn.py
  tests/ml/test_ml_model_pytest.py
Labels: topic:ml

#466 Add authentication methods for import model script
  docs/guide/machine-learning.asciidoc
Labels: documentation

#467 [DOCS] Add question_answering NLP task type
  docs/guide/machine-learning.asciidoc
Labels: documentation

#468 [DOCS] Include missing attributes
  docs/guide/index.asciidoc
Labels: documentation
