Repository elastic/eland, pull requests merged in 2022-06, with the labels that each got.

#472 [ML] ensure quantization is applied
  eland/ml/pytorch/traceable_model.py
Labels: bug, topic:ml

#474 Bump PyTorch version to 1.11
  requirements-dev.txt
  setup.py
Labels: enhancement, topic:ml

#475 [ML] adds new auto task type that attempts to automatically determine NLP task type from model config
  bin/eland_import_hub_model
  eland/ml/pytorch/__init__.py
  eland/ml/pytorch/transformers.py
  tests/ml/pytorch/test_transformer_pytorch_model_pytest.py
Labels: enhancement, topic:ml

#478 Add more exclusions to the dockerignore file
  .dockerignore
Labels: enhancement

#477 Update python example
  docs/guide/machine-learning.asciidoc
Labels: documentation, topic:ml
