Repository elastic/eland, pull requests merged in 2023-07, with the labels that each got.

#558 Fix failing unit tests
  eland/ml/exporters/_sklearn_deserializers.py
  requirements-dev.txt
  setup.py
  tests/ml/pytorch/test_pytorch_model_upload_pytest.py
Labels: refactor

#556 [ML] Update trained model inference endpoint
  README.md
  eland/ml/pytorch/_pytorch_model.py
Labels: topic:ml

#515 Add Buildkite configuration
  .buildkite/Dockerfile
  .buildkite/build-documentation.sh
  .buildkite/lint-code.sh
  .buildkite/pipeline.yml
  .buildkite/run-elasticsearch.sh
  .buildkite/run-repository.sh
  .buildkite/run-tests
  .github/workflows/ci.yml
Labels: ci

#570 [CI] Adds buildkite pull requests configuration
  .buildkite/pull-requests.json
Labels: ci

#569 Simplify embedding model support and loading
  eland/ml/pytorch/transformers.py
Labels: bug, enhancement, topic:ml
