Repository elastic/eland, pull requests merged in 2023-10, with the labels that each got.

#613 Add Buildkite pipeline to push Docker image
  .buildkite/release-docker/pipeline.yml
  .buildkite/release-docker/run.sh
  .readthedocs.yml
  Dockerfile
  eland/dataframe.py
  eland/ml/_optional.py
  setup.py
  utils/generate-supported-apis.py
Labels: ci

#603 Use _append instead of append since it's still available after pandas 2.0.0
  tests/etl/test_pandas_to_eland.py
Labels: topic:dataframe

#623 [NLP] Tests for NLP model configurations
  eland/common.py
  eland/ml/pytorch/__init__.py
  eland/ml/pytorch/nlp_ml_model.py
  eland/ml/pytorch/transformers.py
  tests/ml/pytorch/test_pytorch_model_config.py
  tests/ml/pytorch/test_transformer_pytorch_model_pytest.py
Labels: topic:NLP

#625 [NLP] Support E5 small multi-lingual
  eland/ml/pytorch/__init__.py
  eland/ml/pytorch/transformers.py
  tests/ml/pytorch/test_pytorch_model_config_pytest.py
Labels: topic:NLP
