Repository elastic/eland, pull requests merged in 2023-05, with the labels that each got.

#539 Use compatible versions of numpy and shap
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: bug, topic:dataframe

#522 Upgrade torch to 1.13.1 and check the cluster version before uploading a NLP model.
  README.md
  bin/eland_import_hub_model
  noxfile.py
  requirements-dev.txt
  setup.py
  tests/ml/pytorch/test_pytorch_model_upload_pytest.py
Labels: topic:ml

#541 Generate valid model id from file path
  eland/ml/pytorch/transformers.py
  tests/ml/pytorch/test_transformer_pytorch_model_pytest.py
Labels: topic:ml

#542 [DOCS] Adds instructions on model install in air-gapped env
  docs/guide/machine-learning.asciidoc
Labels: documentation

#543 Add Elasticsearch 8.8 snapshot to test matrix
  .ci/run-elasticsearch.sh
  .ci/test-matrix.yml
Labels: ci
