Repository elastic/eland, pull requests merged in 2023-09, with the labels that each got.

#587 Fix downloads badge URL
  README.md
Labels: documentation

#573 Error measuring embedding size for some DPR models
  eland/ml/pytorch/transformers.py
Labels: bug, topic:ml

#608 Allow importing private HuggingFace models
  docs/guide/machine-learning.asciidoc
  eland/cli/eland_import_hub_model.py
  eland/ml/pytorch/transformers.py
Labels: enhancement
