Repository elastic/eland, pull requests merged in 2025-02, with the labels that each got.

#744 Remove ML model export as sklearn Pipeline and clean up code
  CONTRIBUTING.md
  eland/ml/exporters/__init__.py
  eland/ml/exporters/_sklearn_deserializers.py
  eland/ml/exporters/common.py
  eland/ml/exporters/es_gb_models.py
  eland/ml/ml_model.py
  noxfile.py
  requirements-dev.txt
  tests/ml/test_ml_model_pytest.py
Labels: refactor, topic:ml

#752 Fix tracing baai/bge-m3
  eland/ml/pytorch/transformers.py
  setup.py
Labels: backport 8.x

#761 [docs] Add the new docs CI checks
  .github/workflows/comment-on-asciidoc-changes.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: documentation

#762 [docs] Migrate docs from AsciiDoc to Markdown
  docs/docset.yml
  docs/guide/index.asciidoc
  docs/guide/installation.asciidoc
  docs/guide/machine-learning.asciidoc
  docs/reference/dataframes.md
  docs/reference/index.md
  docs/reference/installation.md
  docs/reference/machine-learning.md
  docs/reference/toc.yml
Labels: documentation
