Repository elastic/eland, pull requests merged in 2025-04, with the labels that each got.

#769 Fix tokeniser for DeBERTa models
  eland/ml/pytorch/_pytorch_model.py
  eland/ml/pytorch/nlp_ml_model.py
  eland/ml/pytorch/transformers.py
  eland/ml/pytorch/wrappers.py
  tests/ml/pytorch/test_pytorch_model_config_pytest.py
  tests/ml/pytorch/test_pytorch_model_upload_pytest.py
Labels: topic:NLP, backport 8.x

#777 Add 9.1.0 Snapshot to Build and Fix test_ml_model Tests to Normalized Expected Scores if Min Score is Less Than Zero
  .buildkite/pipeline.yml
  eland/ml/_model_serializer.py
  tests/ml/test_ml_model_pytest.py
Labels: backport 8.x

#779 Run PyTorch tests on 3.12 too
  noxfile.py
Labels: backport 8.x

#782 Allow lightgbm 4.6.0
  setup.py
Labels: backport 8.x

#781 Update instructions to run ML tests with Elasticsearch
  CONTRIBUTING.md
Labels: backport 8.x

#785 Upgrade PyTorch to 2.5.1
  Dockerfile
  Dockerfile.wolfi
  setup.py
Labels: enhancement, topic:NLP, backport 8.x

#792 Remove redundant version checks in tests
  tests/ml/pytorch/test_pytorch_model_config_pytest.py
  tests/ml/pytorch/test_pytorch_model_upload_pytest.py
Labels: ci
